#!/bin/bash

LOCAL_FILE="/path/to/local/file.txt"
HDFS_PATH="/user/youruser/data/file.txt"

while true; do
    echo "[$(date)] Copying $LOCAL_FILE to HDFS at $HDFS_PATH ..."
    hdfs dfs -copyFromLocal -f "$LOCAL_FILE" "$HDFS_PATH"
    if [ $? -eq 0 ]; then
        echo "[$(date)] File copied successfully!"
    else
        echo "[$(date)] Failed to copy file!"
    fi
    echo "Sleeping for 10 minutes before next copy..."
    sleep 600   # 10 minutes
done
